syntax = "proto3";
package ET;


message ObjectQueryResponse // IActorResponse
{
	int32 RpcId = 90;
	int32 Error = 91;
	string Message = 92;

	Entity entity = 1;
}


//ResponseType M2M_UnitTransferResponse
message M2M_UnitTransferRequest // IActorRequest
{
	int32 RpcId = 1;
	Unit Unit = 2;
	repeated Entity Entitys = 3;
}



//获取unit的数据从数据库
message U2G_GetUnitChache // IActorResponse
{
	int32 RpcId = 90;
	int32 Error = 91;
	string Message = 92;


	repeated  Entity EntityType = 2;  //实体列表
	repeated  string listComponentName = 3;  // 实体组件标识
}

//从map服务器出发,更新玩家排行榜数据，到数据库
message  M2Rank_UpdateRankInfo //IActorRankMessage
{
	int32 RpcId = 90;
	MRankInfo RankInfo = 1;
}